# Generated by Django 5.2.2 on 2025-06-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.AlterField(
            model_name='post',
            name='imageId',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
